"""
HTML visualization handler.

Instead of executing Python code server-side, the LLM generates a
self-contained HTML page (with inline JS using CDN libraries such as
Chart.js, Plotly.js, or D3). This module simply saves that HTML string
to disk and injects the auto-resize postMessage script so the parent
iframe can resize itself automatically.

No subprocess, no AST safety checks, no execution timeout —
the HTML runs entirely inside the browser's own sandbox (iframe with
sandbox="allow-scripts").
"""

import logging
import os
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

logger = logging.getLogger(__name__)

# Root directory where all viz outputs live. Shared with python_executor so
# the existing /viz/{exec_id} serve endpoint works unchanged.
VIZ_ROOT = Path(os.environ.get("VIZ_OUTPUT_ROOT", "/tmp/viz_outputs"))


# ---------------------------------------------------------------------------
# Structured result (mirrors python_executor.VizResult)
# ---------------------------------------------------------------------------


@dataclass
class VizResult:
    """Structured outcome of an HTML visualization save attempt.

    ``exec_id`` is non-None whenever a file was written (even on save_error,
    so callers can correlate logs). ``reason`` explains the outcome.
    """

    exec_id: str | None = None
    reason: Literal["ok", "empty", "save_error"] = "ok"
    stderr: str | None = None
    exit_code: int | None = None  # kept for API compatibility; always None here

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
# Auto-resize postMessage script
# ---------------------------------------------------------------------------
# Injected into every output HTML so the parent React component can resize
# the iframe to fit the content without a fixed height.

_RESIZE_SCRIPT = """<script>
(function () {
  // Force scrollable overflow — some viz libraries (Plotly, etc.) inject
  // overflow:hidden on html/body which prevents the iframe from scrolling.
  document.documentElement.style.overflow = "auto";
  if (document.body) document.body.style.overflow = "auto";

  var _lastH = 0;
  function sendHeight() {
    var h = Math.max(
      document.body ? document.body.scrollHeight : 0,
      document.documentElement ? document.documentElement.scrollHeight : 0
    );
    if (h !== _lastH) {
      _lastH = h;
      window.parent.postMessage({ type: "viz-resize", height: h }, "*");
    }
  }

  // Initial measurement after DOM is ready.
  if (document.readyState === "complete") {
    sendHeight();
  } else {
    window.addEventListener("load", sendHeight);
  }

  // Continuous measurement via ResizeObserver — catches async CDN renders
  // (Chart.js, Plotly CDN, D3 transitions, etc.).
  if (typeof ResizeObserver !== "undefined") {
    new ResizeObserver(sendHeight).observe(document.documentElement);
    if (document.body) new ResizeObserver(sendHeight).observe(document.body);
  }

  // Belt-and-suspenders: periodic re-check for the first few seconds after
  // load, covering edge cases where neither load nor ResizeObserver fires.
  var _checks = 0;
  var _timer = setInterval(function () {
    sendHeight();
    if (++_checks >= 10) clearInterval(_timer);
  }, 500);
})();
</script>"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def save_html_visualization(html: str) -> VizResult:
    """Save a self-contained HTML visualization to disk.

    The HTML is expected to be a complete page generated by the LLM using
    CDN libraries (Chart.js, Plotly.js, D3, etc.). The auto-resize
    postMessage script is injected so the parent iframe can size itself.

    Returns a :class:`VizResult`. On success, ``exec_id`` identifies the
    saved file accessible via the ``/viz/{exec_id}`` endpoint.
    """
    html = html.strip()
    if not html:
        logger.warning("Empty HTML visualization received — skipping save.")
        return VizResult(exec_id=None, reason="empty", stderr="LLM returned empty HTML")

    exec_id = str(uuid.uuid4())
    exec_dir = VIZ_ROOT / exec_id
    try:
        exec_dir.mkdir(parents=True, exist_ok=True)
        output_path = exec_dir / "output.html"

        # Inject resize script before </body>, or append if tag is absent.
        if "</body>" in html:
            html_out = html.replace("</body>", _RESIZE_SCRIPT + "\n</body>", 1)
        else:
            html_out = html + "\n" + _RESIZE_SCRIPT

        output_path.write_text(html_out, encoding="utf-8")
        logger.info(
            "HTML visualization saved: exec_id=%s (%d bytes)", exec_id, len(html_out)
        )
        return VizResult(exec_id=exec_id, reason="ok")
    except Exception as exc:
        logger.error("Failed to save HTML visualization (exec_id=%s): %s", exec_id, exc)
        return VizResult(exec_id=exec_id, reason="save_error", stderr=str(exc))
